# 站点设置
title: "Rin's Blog"
description: "Welcome to my blog"
baseurl: "" # 通常留空
url: "https://rainrin-097.github.io" # 替换为你的实际用户名

# 构建设置
remote_theme: pages-themes/cayman@v0.2.0
plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one

# 作者信息
author:
  name: "Rin"
