# 站点设置
title: "Rin's Blog"
description: "Welcome to my blog"
baseurl: ""
url: "https://rainrin-097.github.io"

# 构建设置
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Cayman 主题配置
show_downloads: false

# 网站地图（可选）
sitemap: true

# 作者信息
author:
  name: "Rin"
