# 站点设置
title: "Rin' Blog"
description: "Welcome to my blog"
baseurl: "" # 通常留空
url: "https://rainrin-097.github.io" # 替换为你的实际用户名

# 构建设置
theme: minima
plugins:
  - jekyll-feed

# 作者信息
author:
  name: "Rin"
